version: '3.9'
services:
  mozbot-db:
    image: postgres:13
    restart: always
    volumes:
      - ${PWD}/.mozbot-build/database:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=mozbot
      - POSTGRES_PASSWORD=mozbot
  mozbot-builder:
    build:
      context: .
      args:
        - SCOPE=builder
    depends_on:
      - mozbot-db
    ports:
      - '8080:3000'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    env_file: .env
  mozbot-viewer:
    build:
      context: .
      args:
        - SCOPE=viewer
    ports:
      - '8081:3000'
    env_file: .env
