version: '3.3'

volumes:
  db-data:

services:
  mozbot-db:
    image: postgres:14-alpine
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=mozbot
      - POSTGRES_PASSWORD=mozbot

  mozbot-builder:
    image: baptistearno/mozbot-builder:latest
    restart: always
    depends_on:
      - mozbot-db
    ports:
      - '8080:3000'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    env_file: .env

  mozbot-viewer:
    image: baptistearno/mozbot-viewer:latest
    restart: always
    ports:
      - '8081:3000'
    env_file: .env
