// Do not edit this file manually
import { parseBlockCredentials, parseBlockSchema } from '@mozbot.io/forge'
import { zemanticAiBlock } from '.'
import { auth } from './auth'

export const zemanticAiBlockSchema = parseBlockSchema(zemanticAiBlock)
export const zemanticAiCredentialsSchema = parseBlockCredentials(
  zemanticAiBlock.id,
  auth.schema
)
