// Do not edit this file manually
import { parseBlockCredentials, parseBlockSchema } from '@mozbot.io/forge'
import { anthropicBlock } from '.'
import { auth } from './auth'

export const anthropicBlockSchema = parseBlockSchema(anthropicBlock)
export const anthropicCredentialsSchema = parseBlockCredentials(
  anthropicBlock.id,
  auth.schema
)
