// Do not edit this file manually
import { anthropicBlock } from '@mozbot.io/anthropic-block'
import { anthropicBlockSchema } from '@mozbot.io/anthropic-block/schemas'
import { calComBlock } from '@mozbot.io/cal-com-block'
import { calComBlockSchema } from '@mozbot.io/cal-com-block/schemas'
import { chatNodeBlock } from '@mozbot.io/chat-node-block'
import { chatNodeBlockSchema } from '@mozbot.io/chat-node-block/schemas'
import { difyAiBlock } from '@mozbot.io/dify-ai-block'
import { difyAiBlockSchema } from '@mozbot.io/dify-ai-block/schemas'
import { elevenlabsBlock } from '@mozbot.io/elevenlabs-block'
import { elevenlabsBlockSchema } from '@mozbot.io/elevenlabs-block/schemas'
import { mistralBlock } from '@mozbot.io/mistral-block'
import { mistralBlockSchema } from '@mozbot.io/mistral-block/schemas'
import { openRouterBlock } from '@mozbot.io/open-router-block'
import { openRouterBlockSchema } from '@mozbot.io/open-router-block/schemas'
import { openAIBlock } from '@mozbot.io/openai-block'
import { openAIBlockSchema } from '@mozbot.io/openai-block/schemas'
import { qrCodeBlock } from '@mozbot.io/qrcode-block'
import { qrCodeBlockSchema } from '@mozbot.io/qrcode-block/schemas'
import { togetherAiBlock } from '@mozbot.io/together-ai-block'
import { togetherAiBlockSchema } from '@mozbot.io/together-ai-block/schemas'
import { nocodbBlock } from '@mozbot.io/nocodb-block'
import { nocodbBlockSchema } from '@mozbot.io/nocodb-block/schemas'

export const forgedBlockSchemas = {
  [openAIBlock.id]: openAIBlockSchema,
  [calComBlock.id]: calComBlockSchema,
  [chatNodeBlock.id]: chatNodeBlockSchema,
  [qrCodeBlock.id]: qrCodeBlockSchema,
  [difyAiBlock.id]: difyAiBlockSchema,
  [mistralBlock.id]: mistralBlockSchema,
  [elevenlabsBlock.id]: elevenlabsBlockSchema,
  [anthropicBlock.id]: anthropicBlockSchema,
  [togetherAiBlock.id]: togetherAiBlockSchema,
  [openRouterBlock.id]: openRouterBlockSchema,
  [nocodbBlock.id]: nocodbBlockSchema,
}
