name: Publish mozbot-js to NPM

on:
  push:
    tags:
      - 'js-lib-v*'

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v4
      - run: pnpm i --frozen-lockfile
      - run: pnpm turbo build --filter=mozbot-js...
      - name: Set NPM_TOKEN in config
        run: pnpm config set //registry.npmjs.org/:_authToken ${NPM_TOKEN}
        working-directory: ./packages/mozbot-js
      - name: Publish
        run: pnpm publish --no-git-checks --access public
        working-directory: ./packages/mozbot-js
